from typing import Protocol


class PrivacyScopePort(Protocol):
    async def readiness(self) -> None: ...

    async def create(self, workspace_root: str) -> str: ...

    async def validate(self, scope_id: str) -> None: ...

    async def delete(self, scope_id: str) -> None: ...

    async def fork(self, scope_id: str) -> str: ...

    async def add_workspace(self, scope_id: str, workspace_root: str) -> None: ...
